/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { Ref, useEffect, useRef } from "react";
import { useGLTF, useAnimations, useFBO } from "@react-three/drei";
import { glassMaterial } from "./utils/glassMaterial";
import { useFrame } from "@react-three/fiber";
import { loadingGeneralVideo } from "./utils/loadingAssets";
import { Mesh } from "three";
import { useAppSelector } from "../../app/store";
import { selectCurrentProject } from "../../app/features/projectSlice";

export function Model(props: any) {
  const group = useRef();
  // @ts-ignore
  const { nodes, materials, animations } = useGLTF("/models/model1.glb");
  const { actions } = useAnimations(animations, group);
  const curProject = useAppSelector(selectCurrentProject);

  const monitor1Ref = useRef<Mesh>();
  const monitor2Ref = useRef<Mesh>();
  const laptopRef = useRef<Mesh>();
  const tvRef = useRef<Mesh>();

  useFrame(() => {
    animations.forEach((animation) => {
      const animationName = animation.name;
      actions[animationName]!.play();
    });
  });

  useEffect(() => {
    tvRef.current!.material = loadingGeneralVideo(curProject?.videoSrc);
    // monitor1Ref.current!.material = loadingGeneralVideo(curProject?.videoSrc);
    // monitor2Ref.current!.material = loadingGeneralVideo(curProject?.videoSrc);
  }, [curProject]);

  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      position={[0, -0.2, 0]}
      scale={[0.1, 0.1, 0.1]}
    >
      <group name="Scene" castShadow receiveShadow>
        <group name="Empty" position={[13.17, 0.34, 15.53]} />
        <group name="Empty001" position={[15.42, -2.61, 12.44]} />
        <mesh
          name="Cube014"
          geometry={nodes.Cube014.geometry}
          material={materials["Material.006"]}
          position={[13.54, 1.64, 0.2]}
        />
        <mesh
          name="trash"
          geometry={nodes.trash.geometry}
          material={materials["Material.002"]}
          position={[12.35, 2.43, 3.1]}
        />
        <mesh
          name="Cube015"
          geometry={nodes.Cube015.geometry}
          material={materials["Material.005"]}
          position={[28.58, 2.41, 7.47]}
        />
        <group name="Cube016" position={[28.41, 3.61, 7.47]}>
          <mesh
            name="Cube017_1"
            geometry={nodes.Cube017_1.geometry}
            material={materials["Material.004"]}
          />
          <mesh
            name="Cube017_2"
            geometry={nodes.Cube017_2.geometry}
            material={materials["Material.005"]}
          />
        </group>
        <mesh
          name="Cube"
          geometry={nodes.Cube.geometry}
          material={materials["table-top"]}
          position={[17.27, 6.2, -0.14]}
        />
        <mesh
          name="Cube001"
          geometry={nodes.Cube001.geometry}
          material={materials["table-top"]}
          position={[27.95, 6.21, 0.59]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          name="Cube002"
          geometry={nodes.Cube002.geometry}
          material={materials["table-top"]}
          position={[28.66, 6.21, 7.63]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          name="Cube003"
          geometry={nodes.Cube003.geometry}
          material={materials["table-top"]}
          position={[19.5, 6.77, -1.99]}
        />
        <mesh
          name="Cube004"
          geometry={nodes.Cube004.geometry}
          material={materials["Material.001"]}
          position={[28.65, 2.5, 9.88]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          name="Cube005"
          geometry={nodes.Cube005.geometry}
          material={materials["table-top"]}
          position={[30.16, 6.77, -1.67]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          name="Cube006"
          geometry={nodes.Cube006.geometry}
          material={materials["table-top"]}
          position={[30.48, 6.77, 5.39]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          name="Cube007"
          geometry={nodes.Cube007.geometry}
          material={materials["table-top"]}
          position={[30.48, 6.53, 10.56]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          name="Cube008"
          geometry={nodes.Cube008.geometry}
          material={materials["table-top"]}
          position={[30.48, 6.53, 3.13]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          name="Cube009"
          geometry={nodes.Cube009.geometry}
          material={materials["table-top"]}
          position={[30.48, 6.53, 0.05]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          name="Cube011"
          geometry={nodes.Cube011.geometry}
          material={materials["table-top"]}
          position={[28.37, 6.53, -2.06]}
          rotation={[Math.PI, 0, Math.PI]}
        />
        <mesh
          name="Cube012"
          geometry={nodes.Cube012.geometry}
          material={materials["table-top"]}
          position={[23.93, 6.53, -2.06]}
          rotation={[Math.PI, 0, Math.PI]}
        />
        <mesh
          name="Cube013"
          geometry={nodes.Cube013.geometry}
          material={materials["table-top"]}
          position={[10.72, 6.53, -2.06]}
          rotation={[Math.PI, 0, Math.PI]}
        />
        <mesh
          name="Cube018"
          geometry={nodes.Cube018.geometry}
          material={materials["Material.001"]}
          position={[21.7, 8.56, -0.87]}
          rotation={[-1.57, 0, 3.11]}
        />
        <mesh
          name="blacksteel"
          geometry={nodes.blacksteel.geometry}
          material={materials["Material.001"]}
          position={[19.05, 6.91, -1.46]}
          rotation={[3.14, 0.01, 3.14]}
        />
        <mesh
          name="Cylinder001"
          geometry={nodes.Cylinder001.geometry}
          material={materials["Material.007"]}
          position={[19.04, 8.5, -1.46]}
          rotation={[0.02, -1.45, 0.03]}
        />
        <mesh
          name="Cylinder002"
          geometry={nodes.Cylinder002.geometry}
          material={nodes.Cylinder002.material}
          position={[19.05, 8.02, -1.46]}
          rotation={[3.14, 0.01, 3.14]}
        />
        <mesh
          name="Cylinder003"
          geometry={nodes.Cylinder003.geometry}
          material={materials["Material.001"]}
          position={[19.22, 8.69, -1.52]}
          rotation={[-3.14, 1.07, -0.01]}
        />
        <mesh
          name="Cylinder004"
          geometry={nodes.Cylinder004.geometry}
          material={materials["Material.007"]}
          position={[19.05, 8.65, -1.46]}
          rotation={[-0.05, 1.5, -3.1]}
        />
        <mesh
          name="Cylinder005"
          geometry={nodes.Cylinder005.geometry}
          material={materials["Material.001"]}
          position={[18.84, 8.44, -1.52]}
          rotation={[3.14, -1.07, 3.14]}
        />
        <mesh
          name="Cube017"
          geometry={nodes.Cube017.geometry}
          material={materials["Material.001"]}
          position={[19.04, 8.1, -0.45]}
          rotation={[-1.57, 0, 3.12]}
        />
        <mesh
          name="screen-1"
          ref={monitor1Ref as Ref<Mesh>}
          geometry={nodes["screen-1"].geometry}
          material={materials.screen}
          position={[21.7, 8.56, -0.55]}
          rotation={[-1.57, 0, 3.12]}
        />
        <mesh
          name="screen-2"
          ref={monitor2Ref as Ref<Mesh>}
          geometry={nodes["screen-2"].geometry}
          material={materials.screen}
          position={[21.7, 8.56, -0.55]}
          rotation={[-1.57, 0, 3.12]}
        />
        <mesh
          name="Cube010"
          geometry={nodes.Cube010.geometry}
          material={materials["Material.010"]}
          position={[19.52, 6.35, 1.48]}
          rotation={[Math.PI, 0, Math.PI]}
        />
        <mesh
          name="Cube019"
          geometry={nodes.Cube019.geometry}
          material={materials["Material.011"]}
          position={[18.89, 6.39, 1.63]}
          rotation={[Math.PI, 0, Math.PI]}
        />
        <group
          name="Cube020"
          position={[17.76, 6.55, 1.17]}
          rotation={[-3.02, 0, -Math.PI]}
        >
          <mesh
            name="Cube026_1"
            geometry={nodes.Cube026_1.geometry}
            material={materials["Material.012"]}
          />
          <mesh
            name="Cube026_2"
            geometry={nodes.Cube026_2.geometry}
            material={materials["Material.013"]}
          />
          <mesh
            name="Cube026_3"
            geometry={nodes.Cube026_3.geometry}
            material={materials["Material.014"]}
          />
          <mesh
            name="Cube026_4"
            geometry={nodes.Cube026_4.geometry}
            material={materials["Material.015"]}
          />
          <mesh
            name="Cube026_5"
            geometry={nodes.Cube026_5.geometry}
            material={materials["Material.016"]}
          />
        </group>
        <group
          name="Cube021"
          position={[17.76, 6.55, 1.17]}
          rotation={[-3.02, 0, -Math.PI]}
        >
          <mesh
            name="Cube027_1"
            geometry={nodes.Cube027_1.geometry}
            material={materials["Material.012"]}
          />
          <mesh
            name="Cube027_2"
            geometry={nodes.Cube027_2.geometry}
            material={materials["Material.013"]}
          />
        </group>
        <group
          name="Cube022"
          position={[21, 6.44, 1.52]}
          rotation={[Math.PI, 0, Math.PI]}
        >
          <mesh
            name="Cube028_1"
            geometry={nodes.Cube028_1.geometry}
            material={materials["Material.011"]}
          />
          <mesh
            name="Cube028_2"
            geometry={nodes.Cube028_2.geometry}
            material={materials["Material.017"]}
          />
        </group>
        <group name="Cylinder" position={[15, 10.38, 2.49]}>
          <mesh
            name="Cylinder008_1"
            geometry={nodes.Cylinder008_1.geometry}
            material={materials["Material.019"]}
          />
          <mesh
            name="Cylinder008_2"
            geometry={nodes.Cylinder008_2.geometry}
            material={materials["Material.018"]}
          />
        </group>
        <mesh
          name="Cylinder006"
          geometry={nodes.Cylinder006.geometry}
          material={materials["Material.020"]}
          position={[15, 6.37, 1.55]}
        />
        <group name="Cube023" position={[13.35, 7.52, -1.73]}>
          <mesh
            name="Cube030_1"
            geometry={nodes.Cube030_1.geometry}
            material={materials["Material.021"]}
          />
          <mesh
            name="Cube030_2"
            geometry={nodes.Cube030_2.geometry}
            material={materials["Material.022"]}
          />
          <mesh
            name="Cube030_3"
            geometry={nodes.Cube030_3.geometry}
            material={materials["Material.023"]}
          />
          <mesh
            name="Cube030_4"
            geometry={nodes.Cube030_4.geometry}
            material={materials["Material.024"]}
          />
        </group>
        <mesh
          name="Cylinder007"
          geometry={nodes.Cylinder007.geometry}
          material={materials["Material.025"]}
          position={[13.1, 6.94, -0.98]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <group name="Cylinder008" position={[30.07, 6.89, 4.23]}>
          <mesh
            name="Cylinder011_1"
            geometry={nodes.Cylinder011_1.geometry}
            material={materials["Material.026"]}
          />
          <mesh
            name="Cylinder011_2"
            geometry={nodes.Cylinder011_2.geometry}
            material={materials["Material.027"]}
          />
        </group>
        <group name="Cylinder009" position={[11.56, 6.89, -1.61]}>
          <mesh
            name="Cylinder012_1"
            geometry={nodes.Cylinder012_1.geometry}
            material={materials["Material.026"]}
          />
          <mesh
            name="Cylinder012_2"
            geometry={nodes.Cylinder012_2.geometry}
            material={materials["Material.027"]}
          />
        </group>
        <group name="Cylinder078" position={[25.68, 17.01, -1.98]}>
          <mesh
            name="Cylinder085"
            geometry={nodes.Cylinder085.geometry}
            material={materials["Material.026"]}
          />
          <mesh
            name="Cylinder085_1"
            geometry={nodes.Cylinder085_1.geometry}
            material={materials["Material.027"]}
          />
        </group>
        <mesh
          name="aqu-inner-lamp"
          geometry={nodes["aqu-inner-lamp"].geometry}
          material={glassMaterial(0x549dd2)}
          position={[-0.1, 9.59, -0.03]}
        />
        <mesh
          name="lamp-1"
          geometry={nodes["lamp-1"].geometry}
          material={glassMaterial(0xffaa00)}
          position={[30.07, 6.89, 4.23]}
        />
        <mesh
          name="lamp-2"
          geometry={nodes["lamp-2"].geometry}
          material={glassMaterial(0xffaa00)}
          position={[11.56, 6.89, -1.61]}
        />
        <mesh
          name="lamp-3"
          geometry={nodes["lamp-3"].geometry}
          material={glassMaterial(0xffaa00)}
          position={[25.68, 17.01, -1.98]}
        />
        <mesh
          name="Cylinder010"
          geometry={nodes.Cylinder010.geometry}
          material={materials["Material.028"]}
          position={[29.97, 6.93, -1.33]}
          rotation={[0, 0.73, 0]}
        />
        <group
          name="Cylinder011"
          position={[30.19, 8.87, -1.5]}
          rotation={[0, -0.84, 0]}
        >
          <mesh
            name="Cylinder014_1"
            geometry={nodes.Cylinder014_1.geometry}
            material={materials["Material.028"]}
          />
          <mesh
            name="Cylinder014_2"
            geometry={nodes.Cylinder014_2.geometry}
            material={materials["Material.029"]}
          />
          <mesh
            name="Cylinder014_3"
            geometry={nodes.Cylinder014_3.geometry}
            material={materials["Material.030"]}
          />
        </group>
        <group
          name="Cube025"
          position={[26.03, 6.4, 2.91]}
          rotation={[-Math.PI, 0.22, -Math.PI]}
        >
          <mesh
            name="Cube035_1"
            geometry={nodes.Cube035_1.geometry}
            material={materials["Material.037"]}
          />
          <mesh
            name="Cube035_2"
            geometry={nodes.Cube035_2.geometry}
            material={materials["Material.038"]}
          />
        </group>
        <group
          name="Cube024"
          position={[29.99, 6.97, 1.76]}
          rotation={[-0.44, -1.13, -0.4]}
        >
          <mesh
            name="Cube036_1"
            geometry={nodes.Cube036_1.geometry}
            material={materials["Material.028"]}
          />
          <mesh
            name="Cube036_2"
            geometry={nodes.Cube036_2.geometry}
            material={materials["Material.029"]}
          />
        </group>
        <mesh
          name="Cylinder012"
          geometry={nodes.Cylinder012.geometry}
          material={materials["Material.036"]}
          position={[30.25, 7.05, 1.98]}
          rotation={[-0.44, -1.13, -0.4]}
        />
        <mesh
          name="Cube026"
          geometry={nodes.Cube026.geometry}
          material={materials["Material.036"]}
          position={[30.09, 7.05, 1.41]}
          rotation={[-Math.PI, -0.4, 0.18]}
        />
        <mesh
          name="Cube027"
          geometry={nodes.Cube027.geometry}
          material={materials["Material.036"]}
          position={[30.18, 7.04, 1.45]}
          rotation={[-0.44, -1.13, 2.74]}
        />
        <mesh
          name="Cube028"
          geometry={nodes.Cube028.geometry}
          material={materials["Material.036"]}
          position={[30.23, 7.02, 1.35]}
          rotation={[0, 0.4, 2.96]}
        />
        <mesh
          name="Cube029"
          geometry={nodes.Cube029.geometry}
          material={materials["Material.036"]}
          position={[30.12, 7.04, 1.31]}
          rotation={[2.7, 1.13, 0.4]}
        />
        <mesh
          name="Cube030"
          geometry={nodes.Cube030.geometry}
          material={materials["Material.036"]}
          position={[30.68, 6.89, 1.77]}
          rotation={[-1.64, 0.17, -1.16]}
        />
        <mesh
          name="Cube031"
          geometry={nodes.Cube031.geometry}
          material={materials["Material.040"]}
          position={[26.17, 6.42, 2.28]}
          rotation={[0, -0.22, -Math.PI]}
        />
        <group
          name="Cylinder013"
          position={[26.3, 6.43, 2.31]}
          rotation={[0, -0.22, -Math.PI]}
        >
          <mesh
            name="Cylinder017"
            geometry={nodes.Cylinder017.geometry}
            material={materials["Material.041"]}
          />
          <mesh
            name="Cylinder017_1"
            geometry={nodes.Cylinder017_1.geometry}
            material={materials["Material.042"]}
          />
        </group>
        <mesh
          name="Cylinder014"
          geometry={nodes.Cylinder014.geometry}
          material={materials["Material.039"]}
          position={[26.02, 6.43, 2.25]}
          rotation={[0, -0.22, -Math.PI]}
        />
        <group
          name="Cube032"
          position={[25.89, 6.43, 3.52]}
          rotation={[0, -0.22, -Math.PI]}
        >
          <mesh
            name="Cube044_1"
            geometry={nodes.Cube044_1.geometry}
            material={materials["Material.043"]}
          />
          <mesh
            name="Cube044_2"
            geometry={nodes.Cube044_2.geometry}
            material={materials["Material.044"]}
          />
        </group>
        <mesh
          name="phone-screen"
          geometry={nodes["phone-screen"].geometry}
          material={materials.screen}
          position={[26.03, 6.4, 2.91]}
          rotation={[-Math.PI, 0.22, -Math.PI]}
        />
        <group
          name="Cube033"
          position={[26.87, 6.39, 8.22]}
          rotation={[Math.PI, 0, Math.PI]}
        >
          <mesh
            name="Cube045_1"
            geometry={nodes.Cube045_1.geometry}
            material={materials["Material.045"]}
          />
          <mesh
            name="Cube045_2"
            geometry={nodes.Cube045_2.geometry}
            material={materials["Material.046"]}
          />
          <mesh
            name="Cube045_3"
            geometry={nodes.Cube045_3.geometry}
            material={materials["Material.047"]}
          />
        </group>
        <group
          name="Cube034"
          position={[27.35, 6.45, 7.13]}
          rotation={[0, 1.57, 0]}
        >
          <mesh
            name="Cube046_1"
            geometry={nodes.Cube046_1.geometry}
            material={materials["Material.012"]}
          />
          <mesh
            name="Cube046_2"
            geometry={nodes.Cube046_2.geometry}
            material={materials["Material.013"]}
          />
          <mesh
            name="Cube046_3"
            geometry={nodes.Cube046_3.geometry}
            material={materials["Material.014"]}
          />
          <mesh
            name="Cube046_4"
            geometry={nodes.Cube046_4.geometry}
            material={materials["Material.015"]}
          />
          <mesh
            name="Cube046_5"
            geometry={nodes.Cube046_5.geometry}
            material={materials["Material.016"]}
          />
        </group>
        <group
          name="Cube035"
          position={[27.35, 6.45, 7.13]}
          rotation={[0, 1.57, 0]}
        >
          <mesh
            name="Cube047_1"
            geometry={nodes.Cube047_1.geometry}
            material={materials["Material.012"]}
          />
          <mesh
            name="Cube047_2"
            geometry={nodes.Cube047_2.geometry}
            material={materials["Material.013"]}
          />
        </group>
        <group
          name="Cube036"
          position={[28.14, 7.17, 8.22]}
          rotation={[Math.PI, 0, 2.03]}
        >
          <mesh
            name="Cube048_1"
            geometry={nodes.Cube048_1.geometry}
            material={materials["Material.048"]}
          />
          <mesh
            name="Cube048_2"
            geometry={nodes.Cube048_2.geometry}
            material={materials["Material.049"]}
          />
        </group>
        <mesh
          name="laptop-screen"
          ref={laptopRef as Ref<Mesh>}
          geometry={nodes["laptop-screen"].geometry}
          material={materials.screen}
          position={[28.14, 7.17, 8.22]}
          rotation={[Math.PI, 0, 2.03]}
        />
        <group
          name="Cube037"
          position={[30.16, 7.02, 7.81]}
          rotation={[0, -0.76, 0]}
        >
          <mesh
            name="Cube049_1"
            geometry={nodes.Cube049_1.geometry}
            material={materials["Material.050"]}
          />
          <mesh
            name="Cube049_2"
            geometry={nodes.Cube049_2.geometry}
            material={materials["Material.051"]}
          />
        </group>
        <group name="Cube038" position={[13.16, 0.44, 16.63]}>
          <mesh
            name="Cube050_1"
            geometry={nodes.Cube050_1.geometry}
            material={materials["Material.073"]}
          />
          <mesh
            name="Cube050_2"
            geometry={nodes.Cube050_2.geometry}
            material={materials["Material.003"]}
          />
        </group>
        <mesh
          name="Cube058"
          geometry={nodes.Cube058.geometry}
          material={materials["Material.073"]}
          position={[19.5, 14.3, -1.95]}
        />
        <mesh
          name="Cube059"
          geometry={nodes.Cube059.geometry}
          material={materials["Material.073"]}
          position={[19.55, 16.78, -2.03]}
        />
        <group
          name="Cube060"
          position={[23.4, 14.72, -1.72]}
          rotation={[0, -0.76, 0]}
        >
          <mesh
            name="Cube074"
            geometry={nodes.Cube074.geometry}
            material={materials["Material.050"]}
          />
          <mesh
            name="Cube074_1"
            geometry={nodes.Cube074_1.geometry}
            material={materials["Material.051"]}
          />
          <mesh
            name="Cube074_2"
            geometry={nodes.Cube074_2.geometry}
            material={materials["Material.077"]}
          />
        </group>
        <group
          name="Cylinder074"
          position={[12.48, 18.26, -1.99]}
          rotation={[0, 1.25, 0]}
        >
          <mesh
            name="Cylinder081"
            geometry={nodes.Cylinder081.geometry}
            material={materials["Material.052"]}
          />
          <mesh
            name="Cylinder081_1"
            geometry={nodes.Cylinder081_1.geometry}
            material={materials["Material.053"]}
          />
          <mesh
            name="Cylinder081_2"
            geometry={nodes.Cylinder081_2.geometry}
            material={materials["Material.054"]}
          />
        </group>
        <group
          name="Cube061"
          position={[19.72, 18.1, -2.38]}
          rotation={[1.57, 0.62, -1.57]}
        >
          <mesh
            name="Cube011_1"
            geometry={nodes.Cube011_1.geometry}
            material={materials["Material.050"]}
          />
          <mesh
            name="Cube011_2"
            geometry={nodes.Cube011_2.geometry}
            material={materials["Material.051"]}
          />
        </group>
        <group
          name="Cube062"
          position={[17.84, 18.18, -2.38]}
          rotation={[1.57, 0, -Math.PI / 2]}
        >
          <mesh
            name="Cube018_1"
            geometry={nodes.Cube018_1.geometry}
            material={materials["Material.050"]}
          />
          <mesh
            name="Cube018_2"
            geometry={nodes.Cube018_2.geometry}
            material={materials["Material.051"]}
          />
          <mesh
            name="Cube018_3"
            geometry={nodes.Cube018_3.geometry}
            material={materials["Material.078"]}
          />
          <mesh
            name="Cube018_4"
            geometry={nodes.Cube018_4.geometry}
            material={materials["Material.079"]}
          />
          <mesh
            name="Cube018_5"
            geometry={nodes.Cube018_5.geometry}
            material={materials["Material.080"]}
          />
        </group>
        <mesh
          name="Cube063"
          geometry={nodes.Cube063.geometry}
          material={materials["Material.073"]}
          position={[13.16, 0.44, 16.63]}
        />
        <group
          name="Cylinder020"
          position={[8.28, 4.71, -0.34]}
          rotation={[0, 1.25, 0]}
        >
          <mesh
            name="Cylinder025"
            geometry={nodes.Cylinder025.geometry}
            material={materials["Material.052"]}
          />
          <mesh
            name="Cylinder025_1"
            geometry={nodes.Cylinder025_1.geometry}
            material={materials["Material.053"]}
          />
          <mesh
            name="Cylinder025_2"
            geometry={nodes.Cylinder025_2.geometry}
            material={materials["Material.054"]}
          />
        </group>
        <group name="Cylinder027" position={[29.54, 6.58, 14.17]}>
          <mesh
            name="Cylinder032"
            geometry={nodes.Cylinder032.geometry}
            material={materials["Material.052"]}
          />
          <mesh
            name="Cylinder032_1"
            geometry={nodes.Cylinder032_1.geometry}
            material={materials["Material.053"]}
          />
          <mesh
            name="Cylinder032_2"
            geometry={nodes.Cylinder032_2.geometry}
            material={materials["Material.054"]}
          />
        </group>
        <group
          name="Cylinder056"
          position={[26.45, 8.1, -1.12]}
          rotation={[0, 1.25, 0]}
        >
          <mesh
            name="Cylinder063"
            geometry={nodes.Cylinder063.geometry}
            material={materials["Material.052"]}
          />
          <mesh
            name="Cylinder063_1"
            geometry={nodes.Cylinder063_1.geometry}
            material={materials["Material.053"]}
          />
          <mesh
            name="Cylinder063_2"
            geometry={nodes.Cylinder063_2.geometry}
            material={materials["Material.054"]}
          />
        </group>
        <mesh
          name="Cube039"
          geometry={nodes.Cube039.geometry}
          material={materials["Material.055"]}
          position={[28.62, 8.13, 18.93]}
        />
        <group name="Cube040" position={[28.87, 3.14, 20.02]}>
          <mesh
            name="Cube052_1"
            geometry={nodes.Cube052_1.geometry}
            material={materials["Material.055"]}
          />
          <mesh
            name="Cube052_2"
            geometry={nodes.Cube052_2.geometry}
            material={materials["Material.056"]}
          />
        </group>
        <group name="Cube041" position={[28.87, 3.14, 30.94]}>
          <mesh
            name="Cube053_1"
            geometry={nodes.Cube053_1.geometry}
            material={materials["Material.055"]}
          />
          <mesh
            name="Cube053_2"
            geometry={nodes.Cube053_2.geometry}
            material={materials["Material.057"]}
          />
        </group>
        <group
          name="Cube043"
          position={[26.88, 3.72, 25.73]}
          rotation={[0, -0.76, 0]}
        >
          <mesh
            name="Cube055_1"
            geometry={nodes.Cube055_1.geometry}
            material={materials["Material.050"]}
          />
          <mesh
            name="Cube055_2"
            geometry={nodes.Cube055_2.geometry}
            material={materials["Material.051"]}
          />
          <mesh
            name="Cube055_3"
            geometry={nodes.Cube055_3.geometry}
            material={materials["Material.034"]}
          />
        </group>
        <group
          name="Cube044"
          position={[27.55, 1.71, 23.27]}
          rotation={[0.92, 0, 0]}
        >
          <mesh
            name="Cube056_1"
            geometry={nodes.Cube056_1.geometry}
            material={materials["Material.050"]}
          />
          <mesh
            name="Cube056_2"
            geometry={nodes.Cube056_2.geometry}
            material={materials["Material.051"]}
          />
          <mesh
            name="Cube056_3"
            geometry={nodes.Cube056_3.geometry}
            material={materials["Material.074"]}
          />
          <mesh
            name="Cube056_4"
            geometry={nodes.Cube056_4.geometry}
            material={materials["Material.075"]}
          />
          <mesh
            name="Cube056_5"
            geometry={nodes.Cube056_5.geometry}
            material={materials["Material.076"]}
          />
        </group>
        <group
          name="Cube045"
          position={[27.59, 1.01, 26.89]}
          rotation={[0, 0.01, -0.01]}
        >
          <mesh
            name="Cube057"
            geometry={nodes.Cube057.geometry}
            material={materials["Material.050"]}
          />
          <mesh
            name="Cube057_1"
            geometry={nodes.Cube057_1.geometry}
            material={materials["Material.051"]}
          />
          <mesh
            name="Cube057_2"
            geometry={nodes.Cube057_2.geometry}
            material={materials["Material.035"]}
          />
        </group>
        <mesh
          name="Cube046"
          geometry={nodes.Cube046.geometry}
          material={materials["Material.060"]}
          position={[29.83, 5.93, 30.71]}
          rotation={[Math.PI / 6, 0, 0]}
        />
        <mesh
          name="Cube047"
          geometry={nodes.Cube047.geometry}
          material={materials["Material.060"]}
          position={[29.83, 10.35, 25.56]}
        />
        <mesh
          name="tv-screen"
          ref={tvRef as Ref<Mesh>}
          geometry={nodes["tv-screen"].geometry}
          material={materials.screen}
          position={[29.83, 10.35, 25.56]}
        />
        <mesh
          name="glass_"
          geometry={nodes.glass_.geometry}
          material={glassMaterial(0xffffff)}
          position={[28.86, 3.32, 25.5]}
        />
        <group name="Cube048" position={[17.24, 1.63, 24.76]}>
          <mesh
            name="Cube060_1"
            geometry={nodes.Cube060_1.geometry}
            material={materials["Material.062"]}
          />
          <mesh
            name="Cube060_2"
            geometry={nodes.Cube060_2.geometry}
            material={materials["Material.063"]}
          />
        </group>
        <group
          name="Cube051"
          position={[17.73, 3.16, 23.49]}
          rotation={[-1.57, -0.01, 0.5]}
        >
          <mesh
            name="Cube063_1"
            geometry={nodes.Cube063_1.geometry}
            material={materials["Material.043"]}
          />
          <mesh
            name="Cube063_2"
            geometry={nodes.Cube063_2.geometry}
            material={materials["Material.044"]}
          />
        </group>
        <group
          name="Cylinder042"
          position={[17.39, 3.18, 22.41]}
          rotation={[Math.PI, 1.28, 0]}
        >
          <mesh
            name="Cylinder047_1"
            geometry={nodes.Cylinder047_1.geometry}
            material={materials["Material.041"]}
          />
          <mesh
            name="Cylinder047_2"
            geometry={nodes.Cylinder047_2.geometry}
            material={materials["Material.042"]}
          />
        </group>
        <mesh
          name="Cube049"
          geometry={nodes.Cube049.geometry}
          material={materials["Material.064"]}
          position={[16.76, 3.16, 22.71]}
          rotation={[-Math.PI, 1.06, -Math.PI]}
        />
        <group
          name="Cube050"
          position={[17.48, 3.16, 23.63]}
          rotation={[-1.57, -0.01, 0.5]}
        >
          <mesh
            name="Cube065"
            geometry={nodes.Cube065.geometry}
            material={materials["Material.043"]}
          />
          <mesh
            name="Cube065_1"
            geometry={nodes.Cube065_1.geometry}
            material={materials["Material.044"]}
          />
        </group>
        <mesh
          name="tablet-screen"
          geometry={nodes["tablet-screen"].geometry}
          material={materials.screen}
          position={[16.76, 3.16, 22.71]}
          rotation={[-Math.PI, 1.06, -Math.PI]}
        />
        <group name="Cylinder043" position={[19.2, 1.66, 5.51]}>
          <mesh
            name="Cylinder050"
            geometry={nodes.Cylinder050.geometry}
            material={materials["Material.066"]}
          />
          <mesh
            name="Cylinder050_1"
            geometry={nodes.Cylinder050_1.geometry}
            material={nodes.Cylinder050_1.material}
          />
        </group>
        <group
          name="Cylinder044"
          position={[20.96, 0.63, 2.45]}
          rotation={[Math.PI / 2, 0, 0]}
        >
          <mesh
            name="Cylinder051"
            geometry={nodes.Cylinder051.geometry}
            material={materials["Material.066"]}
          />
          <mesh
            name="Cylinder051_1"
            geometry={nodes.Cylinder051_1.geometry}
            material={materials["Material.067"]}
          />
        </group>
        <group
          name="Cylinder045"
          position={[17.45, 0.63, 8.55]}
          rotation={[Math.PI / 2, 0, Math.PI]}
        >
          <mesh
            name="Cylinder052"
            geometry={nodes.Cylinder052.geometry}
            material={materials["Material.066"]}
          />
          <mesh
            name="Cylinder052_1"
            geometry={nodes.Cylinder052_1.geometry}
            material={materials["Material.067"]}
          />
        </group>
        <group
          name="Cylinder046"
          position={[17.44, 0.63, 2.46]}
          rotation={[Math.PI / 2, 0, -Math.PI / 3]}
        >
          <mesh
            name="Cylinder053"
            geometry={nodes.Cylinder053.geometry}
            material={materials["Material.066"]}
          />
          <mesh
            name="Cylinder053_1"
            geometry={nodes.Cylinder053_1.geometry}
            material={materials["Material.067"]}
          />
        </group>
        <group
          name="Cylinder047"
          position={[20.97, 0.63, 8.55]}
          rotation={[Math.PI / 2, 0, 2.09]}
        >
          <mesh
            name="Cylinder054"
            geometry={nodes.Cylinder054.geometry}
            material={materials["Material.066"]}
          />
          <mesh
            name="Cylinder054_1"
            geometry={nodes.Cylinder054_1.geometry}
            material={materials["Material.067"]}
          />
        </group>
        <group
          name="Cylinder048"
          position={[15.69, 0.63, 5.51]}
          rotation={[Math.PI / 2, 0, -2.09]}
        >
          <mesh
            name="Cylinder055"
            geometry={nodes.Cylinder055.geometry}
            material={materials["Material.066"]}
          />
          <mesh
            name="Cylinder055_1"
            geometry={nodes.Cylinder055_1.geometry}
            material={materials["Material.067"]}
          />
        </group>
        <group
          name="Cylinder049"
          position={[22.72, 0.63, 5.5]}
          rotation={[Math.PI / 2, 0, Math.PI / 3]}
        >
          <mesh
            name="Cylinder056_1"
            geometry={nodes.Cylinder056_1.geometry}
            material={materials["Material.066"]}
          />
          <mesh
            name="Cylinder056_2"
            geometry={nodes.Cylinder056_2.geometry}
            material={materials["Material.067"]}
          />
        </group>
        <group name="chair" position={[19.2, 2.24, 5.52]}>
          <mesh
            name="Cube071"
            geometry={nodes.Cube071.geometry}
            material={materials["Material.069"]}
          />
          <mesh
            name="Cube071_1"
            geometry={nodes.Cube071_1.geometry}
            material={materials["Material.068"]}
          />
          <mesh
            name="Cube071_2"
            geometry={nodes.Cube071_2.geometry}
            material={materials["Material.072"]}
          />
        </group>
        <group name="Cube054" position={[-0.11, 0.52, -0.03]}>
          <mesh
            name="Cube068_1"
            geometry={nodes.Cube068_1.geometry}
            material={materials["Material.070"]}
          />
          <mesh
            name="Cube068_2"
            geometry={nodes.Cube068_2.geometry}
            material={materials["Material.071"]}
          />
          <mesh
            name="Cube068_3"
            geometry={nodes.Cube068_3.geometry}
            material={materials["Material.081"]}
          />
        </group>
        <mesh
          name="rock"
          geometry={nodes.rock.geometry}
          material={materials["Material.089"]}
          position={[-3.71, 10.24, 1.21]}
        />
        <mesh
          name="rock013"
          geometry={nodes.rock013.geometry}
          material={materials["Material.089"]}
          position={[-2.82, 11.02, -0.33]}
        />
        <mesh
          name="rock020"
          geometry={nodes.rock020.geometry}
          material={materials["Material.089"]}
          position={[1.39, 10.25, 1.3]}
        />
        <group name="fish-1" position={[2.1, 11.59, -1.79]}>
          <mesh
            name="Cube020_1"
            geometry={nodes.Cube020_1.geometry}
            material={materials["Material.084"]}
          />
          <mesh
            name="Cube020_2"
            geometry={nodes.Cube020_2.geometry}
            material={materials["Material.086"]}
          />
        </group>
        <group
          name="fish-2"
          position={[-2.82, 12.4, 1.57]}
          rotation={[Math.PI, 0, Math.PI]}
        >
          <mesh
            name="Cube022_1"
            geometry={nodes.Cube022_1.geometry}
            material={materials["Material.085"]}
          />
          <mesh
            name="Cube022_2"
            geometry={nodes.Cube022_2.geometry}
            material={materials["Material.087"]}
          />
        </group>
        <mesh
          name="Cube066"
          geometry={nodes.Cube066.geometry}
          material={materials["Material.088"]}
          position={[-3.22, 10.29, 1.97]}
        />
        <mesh
          name="Cube067"
          geometry={nodes.Cube067.geometry}
          material={materials["Material.088"]}
          position={[-0.56, 10.27, 0.28]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          name="Cube068"
          geometry={nodes.Cube068.geometry}
          material={materials["Material.088"]}
          position={[2.9, 10.32, 1.96]}
          rotation={[0, -0.09, 0]}
        />
        <mesh
          name="Cube069"
          geometry={nodes.Cube069.geometry}
          material={materials["Material.088"]}
          position={[3.04, 10.27, -0.22]}
        />
        <mesh
          name="rock001"
          geometry={nodes.rock001.geometry}
          material={materials["Material.089"]}
          position={[-2.47, 10.14, 1.06]}
        />
        <mesh
          name="rock002"
          geometry={nodes.rock002.geometry}
          material={materials["Material.089"]}
          position={[-3.48, 10.09, -0.97]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="rock003"
          geometry={nodes.rock003.geometry}
          material={materials["Material.089"]}
          position={[-1.37, 10.04, -1.36]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="rock004"
          geometry={nodes.rock004.geometry}
          material={materials["Material.089"]}
          position={[-3.74, 10.1, 0.15]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        />
        <mesh
          name="rock005"
          geometry={nodes.rock005.geometry}
          material={materials["Material.089"]}
          position={[-2.05, 10.32, -0.14]}
        />
        <mesh
          name="rock007"
          geometry={nodes.rock007.geometry}
          material={materials["Material.089"]}
          position={[0.15, 10.19, 1.08]}
        />
        <mesh
          name="rock008"
          geometry={nodes.rock008.geometry}
          material={materials["Material.089"]}
          position={[-0.55, 10.16, -1.13]}
          rotation={[Math.PI / 2, 0, Math.PI / 4]}
        />
        <mesh
          name="rock011"
          geometry={nodes.rock011.geometry}
          material={materials["Material.089"]}
          position={[3.82, 10.07, 0.99]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="rock012"
          geometry={nodes.rock012.geometry}
          material={materials["Material.089"]}
          position={[0.16, 10, -0.49]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="rock014"
          geometry={nodes.rock014.geometry}
          material={materials["Material.089"]}
          position={[2.66, 10.17, 1.24]}
        />
        <mesh
          name="rock015"
          geometry={nodes.rock015.geometry}
          material={materials["Material.089"]}
          position={[2.76, 10.07, -1.02]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="rock016"
          geometry={nodes.rock016.geometry}
          material={materials["Material.089"]}
          position={[1.69, 10.37, -1.3]}
        />
        <mesh
          name="rock017"
          geometry={nodes.rock017.geometry}
          material={materials["Material.089"]}
          position={[1.95, 10.11, -0.21]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="rock019"
          geometry={nodes.rock019.geometry}
          material={materials["Material.089"]}
          position={[3.92, 10.02, -1.34]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="aqu"
          geometry={nodes.aqu.geometry}
          material={glassMaterial(0x549dd2)}
          position={[-0.1, 9.56, -0.02]}
        />
        <group
          name="Cylinder015"
          position={[31.32, 18.15, 11.47]}
          rotation={[0, 0, -Math.PI / 2]}
        >
          <mesh
            name="Cylinder019"
            geometry={nodes.Cylinder019.geometry}
            material={materials["Material.031"]}
          />
          <mesh
            name="Cylinder019_1"
            geometry={nodes.Cylinder019_1.geometry}
            material={materials["Material.020"]}
          />
        </group>
        <mesh
          name="Cube042"
          geometry={nodes.Cube042.geometry}
          material={materials["Material.026"]}
          position={[31.2, 19.41, 11.47]}
          rotation={[Math.PI, 0, -Math.PI / 2]}
        />
        <mesh
          name="Cube052"
          geometry={nodes.Cube052.geometry}
          material={materials["Material.079"]}
          position={[31.2, 18.16, 12.73]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
        />
        <mesh
          name="Cube053"
          geometry={nodes.Cube053.geometry}
          material={materials["Material.026"]}
          position={[31.2, 16.89, 11.47]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          name="Cube055"
          geometry={nodes.Cube055.geometry}
          material={materials["Material.026"]}
          position={[31.2, 18.14, 10.21]}
          rotation={[1.57, 0, -Math.PI / 2]}
        />
        <mesh
          name="Cube056"
          geometry={nodes.Cube056.geometry}
          material={materials["Material.042"]}
          position={[31.19, 18.65, 11.48]}
          rotation={[0, 0, Math.PI / 2]}
        />
        <mesh
          name="Cube070"
          geometry={nodes.Cube070.geometry}
          material={materials["Material.042"]}
          position={[31.19, 17.93, 11.32]}
          rotation={[-2.57, 0, Math.PI / 2]}
        />
        <mesh
          name="Cube072"
          geometry={nodes.Cube072.geometry}
          material={materials["Material.032"]}
          position={[4.16, 3.16, 32.57]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <group
          name="Plane"
          position={[30.11, 7.06, 4.25]}
          rotation={[0, 1.56, 0]}
        >
          <mesh
            name="Plane_1"
            geometry={nodes.Plane_1.geometry}
            material={materials.Material}
          />
          <mesh
            name="Plane_2"
            geometry={nodes.Plane_2.geometry}
            material={materials["Material.020"]}
          />
        </group>
        <group
          name="Plane001"
          position={[11.57, 7.05, -1.58]}
          rotation={[-Math.PI, 0.01, -Math.PI]}
        >
          <mesh
            name="Plane001_1"
            geometry={nodes.Plane001_1.geometry}
            material={materials.Material}
          />
          <mesh
            name="Plane001_2"
            geometry={nodes.Plane001_2.geometry}
            material={materials["Material.020"]}
          />
        </group>
        <group
          name="Plane002"
          position={[25.7, 17.17, -1.97]}
          rotation={[-Math.PI, 0.01, -Math.PI]}
        >
          <mesh
            name="Plane002_1"
            geometry={nodes.Plane002_1.geometry}
            material={materials.Material}
          />
          <mesh
            name="Plane002_2"
            geometry={nodes.Plane002_2.geometry}
            material={materials["Material.020"]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/model1.glb");
